---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/5/2 17:39
---

---@class MatchRule
MatchRule = {}
Type_SpriteRenderer = "UnityEngine.SpriteRenderer"
Type_Image = "UnityEngine.UI.Image"
Type_RawImage = "UnityEngine.UI.RawImage"

---格子宽
---@type number
Grid_WIDTH = 1.4
---格子高
---@type number
Grid_HIGHT = 1.4

---图片宽
---@type number
VIEW_WIDTH = 1080
---图片高
---@type number
VIEW_HEIGHT = 1920
---默认 1920*1080的缩放速度
---@type number
SCALE_HEIGHT = 305

---格子尺寸
---@type number
MatchRule.Size = 4

---匹配物品创建计数器
---@type number
MatchRule.Match_CreateCount = 10

---匹配物品创建计数器
---@type boolean
MatchRule.isUseProp = false

---操作类型
---@class EOperateType
EOperateType = {
    ---还原操作
    None = 0,
    ---使用道具
    Use_Props = 1,
    ---扫除
    Wipe = 2,
    ---两者都是道具
    Both_Props =3
}

---视图层级
---@class EMapLayerView
EMapLayerView = {
    ---默认层级
    None = 0,
    ---底部层级
    Bottom = 1,
    ---顶部层级
    Float= 2
}

---物品类型
---@class EItemType
EItemType = {
    ---普通类型
    Normal = 0,
    ---道具类型
    Item = 1,
    ---障碍物类型
    Obstacle = 2,
}

---道具类型
---@class EPropsType
EPropsType = {
    None = 0,
    ---炸弹：以炸弹当前位置向外扩大2各消除
    Bomb = 1,
    ---蜻蜓：优先随机查找障碍物消除
    Dragonfly = 2,
    ---垂直火箭：行或列消除
    Rocket = 3,
    ---彩虹球：与交换的颜色属性，或随机的颜色属性消除
    RainbowBall = 4,
    ---水平火箭
    Rocket_Horizontal = 5,
    ---交换的对象是物品
    Item = 10,
}

---障碍物类型
---@class EObstacleType
EObstacleType = {
    None = 0,
    ---固定生成且不可消除：获取新的信封或奖励
    Born = 1,
    ---移动消耗：可以交换，自动下落，会被消除
    Move = 2,
    ---固定类型：有消除次数，消除完为止
    Fixed = 3,
    ---动物类型：可以交换，自动下落，中途不可消除，需要下落到底部才消除
    Animal = 4,
    ---背景固定类型：如底部草，草上的物品和普通物品一样可以操作，草上物品消除时才可以被消除
    Glass = 5,
    ---泡泡固定类型：如透明云或泡泡，遮罩的物品和普通物品一样可以操作，遮罩下物品消除时才可以被消除
    Bubble = 6
}

---物品颜色
---@class EColorItem
EColorItem = {
    none = 0,
    ---红色
    red = 1,
    ---黄色
    yellow = 2,
    ---蓝色
    blue = 3,
    ---绿色
    green = 4,
    ---紫色
    purple = 5,
    ---青色
    cyan = 6,
    ---道具消除所有颜色
    all = 10,
}


---场景图集
---@class EAtlasResPath
EAtlasResPath = {
    ---物品图集
    Item = "Atlas/Scene/Item",
    ---场景图集
    Scene = "Atlas/Scene/Scene",
    ---物品图集
    UIHead = "Atlas/UI/UIHead",
}

---场景特效
---@class ESceneEffectRes
ESceneEffectRes ={
    ---旋转特效
    Match_rotation = "effect_match_rotation",
    ---消除特效
    Match_wipe = "effect_match_wipe",
    ---生成道具特效
    Born_props = "effect_match_wipe_props",
    ---彩虹球发射特效
    Rainbowball_fly ="effect_rainbowball_fly",
}

---道具视图
---@class EPropsView
EPropsView = {
    None = 0,
    ---所在列：大炮
    Cell = 1,
    ---所在行:弓箭
    Row = 2,
    ---粉碎坐标：垂直
    Wipe = 3,
    ---随机位置：帽子
    DiceRandom = 4
}

---转换货币类型
---@class EPropsToMoneyType
EPropsToMoneyType = {
    [EPropsView.Row]=EMoneyType.bows,
    [EPropsView.Cell]=EMoneyType.gun,
    [EPropsView.Wipe]=EMoneyType.hammer,
    [EPropsView.DiceRandom]=EMoneyType.cap,
}

---道具购买次数
---@class EPropsBuyCount
EPropsBuyCount = {
    [EPropsView.Row]=EMoneyType.bowsCount,
    [EPropsView.Cell]=EMoneyType.gunCount,
    [EPropsView.Wipe]=EMoneyType.hammerCount,
    [EPropsView.DiceRandom]=EMoneyType.capCount,
}

---道具视图
---@class ETaskType
ETaskType = {
    Normal =  1,
    Props = 2,
    Level = 3,
    Obstacle = 4,
}

---@class EMetaFightState
EMetaFightState = {
    Level = 0,
    Test = 1,
    TestFinish = 2,
    Fight = 3,
    FightFinish = 4,
    Quit = 5,
}