
---athor:hukiry
---this class was generated by tools，Please Don't Modify! 

require('LuaConfig.ConfigurationBase')

---@class SingleConfig
SingleConfig = {}
local m_list = {}
---@private
function SingleConfig._ImportClass(className, classPath)
	if m_list[className] == nil then
		m_list[className] = require(classPath).New()
	end
	return m_list[className]
end

---D-掉落表
---@return TableDropArrayHelp
function SingleConfig.DropArray()
	return SingleConfig._ImportClass('TableDropArrayHelp', 'LuaConfig.DropArray.TableDropArrayHelp')
end

---G-全局配置
---@return TableGlobalHelp
function SingleConfig.Global()
	return SingleConfig._ImportClass('TableGlobalHelp', 'LuaConfig.Global.TableGlobalHelp')
end

---Q-签到
---@return TableSignHelp
function SingleConfig.Sign()
	return SingleConfig._ImportClass('TableSignHelp', 'LuaConfig.Sign.TableSignHelp')
end

---S-商店表
---@return TableShopHelp
function SingleConfig.Shop()
	return SingleConfig._ImportClass('TableShopHelp', 'LuaConfig.Shop.TableShopHelp')
end

---S-商店表
---@return TableRechargeHelp
function SingleConfig.Recharge()
	return SingleConfig._ImportClass('TableRechargeHelp', 'LuaConfig.Recharge.TableRechargeHelp')
end

---S-商店表
---@return TableCurrencyHelp
function SingleConfig.Currency()
	return SingleConfig._ImportClass('TableCurrencyHelp', 'LuaConfig.Currency.TableCurrencyHelp')
end

---T_通行证
---@return TablePassHelp
function SingleConfig.Pass()
	return SingleConfig._ImportClass('TablePassHelp', 'LuaConfig.Pass.TablePassHelp')
end

---W-物品表
---@return TableItemHelp
function SingleConfig.Item()
	return SingleConfig._ImportClass('TableItemHelp', 'LuaConfig.Item.TableItemHelp')
end

---W-物品表
---@return TableItemCoordHelp
function SingleConfig.ItemCoord()
	return SingleConfig._ImportClass('TableItemCoordHelp', 'LuaConfig.ItemCoord.TableItemCoordHelp')
end

---Y-引导剧情
---@return TableGuideHelp
function SingleConfig.Guide()
	return SingleConfig._ImportClass('TableGuideHelp', 'LuaConfig.Guide.TableGuideHelp')
end

---Y-语言对照表
---@return TableMultiLanguageHelp
function SingleConfig.MultiLanguage()
	return SingleConfig._ImportClass('TableMultiLanguageHelp', 'LuaConfig.MultiLanguage.TableMultiLanguageHelp')
end

---Y-语言表
---@return TableLanguageHelp
function SingleConfig.Language()
	return SingleConfig._ImportClass('TableLanguageHelp', 'LuaConfig.Language.TableLanguageHelp')
end
