---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/6/29 13:53
---

---@class MailView:IPageView
local MailView = Class(UIWindowBase)

function MailView:ctor(gameObject)
    self.index = 2
end

---初始界面:注册按钮事件等
function MailView:Start()

    self.contentGo = self:FindGameObject("ScrollView/Viewport/Content")
    ---@type UnityEngine.UI.ContentSizeFitter
    self.contentSize = self.contentGo:GetComponent("ContentSizeFitter")

    self.noMailGo = self:FindGameObject("ScrollView/Viewport/noMail")
    self.noNeworkGo = self:FindGameObject("ScrollView/Viewport/noNetwork")

    self.titleGo = self:FindGameObject("bg")

    ---@type table<number, MailItem>
    self.lifeList = {}
    ---@type table<number, MailItem>
    self.mailList = {}
end

function MailView:OnEnable()
    self:OnDisable()
    local array = SingleData.Mail():GetLifeArray()
    for i, v in ipairs(array) do
        if self.lifeList[i] == nil then
            self.lifeList[i] = UIItemPool.Get(UIItemType.MailItem, self.contentGo, true, Handle(self, self.ClickCall), self)
        end
        self.lifeList[i]:OnEnable(v, i)
    end
    self.isShowNo = #array == 0
    self.noMailGo:SetActive(self.isShowNo and not Single.Http():IsHaveNetwork())
    self.noNeworkGo.gameObject:SetActive(#array==0 and Single.Http():IsHaveNetwork())
    Single.Request().SendMailBoard(true, EHttpMailState.Request,0, Handle(self, self.OnDispatch))
end

---更新邮件信息
function MailView:OnDispatch(isOk)
    local array = SingleData.Mail():GetMailArray()
    if self.isShowNo then
        self.isShowNo = #array == 0
    end

    self.noNeworkGo.gameObject:SetActive(self.isShowNo and Single.Http():IsHaveNetwork())
    self.noMailGo:SetActive(self.isShowNo and not Single.Http():IsHaveNetwork())
    if isOk then
        self.noNeworkGo.gameObject:SetActive(false)
        self.noMailGo:SetActive(self.isShowNo)
    end

    for i, v in ipairs(array) do
        if self.mailList[i] == nil then
            self.mailList[i] = UIItemPool.Get(UIItemType.MailItem, self.contentGo, false, Handle(self, self.ClickCall),self)
        end
        self.mailList[i]:OnEnable(v, i)
    end
end

function MailView:ChangeLanguage()
    for i, v in pairs(self.mailList) do
        v:ChangeLanguage()
    end
end

---点击回调移除数据
---@param isLife boolean 是生命
---@param index number 索引的视图
function MailView:ClickCall(isLife, index)
    if isLife then
        self.lifeList[index] = nil
    else
        self.mailList[index] = nil
    end
    self.noMailGo:SetActive(table.length(self.lifeList)==0 and table.length(self.mailList)==0)
end

---隐藏窗口
function MailView:OnDisable()
    UIItemPool.PutTable(UIItemType.MailItem, self.mailList)
    UIItemPool.PutTable(UIItemType.MailItem, self.lifeList)
end

return MailView