---Generated By Hukiry-lua Do not Edit

---服务器错误处理
---@class MSG_1901
local MSG_1901 = {}
---@private
MSG_1901.fields = {"cmd","code"}
---@private
MSG_1901.fieldType = {11,1}
---@private
MSG_1901.fieldTag = {0,0}
function MSG_1901:_ctor()
	---请求的cmd
	self.cmd = 0
	---错误码
	self.code = 0
end

msg_1901 = protobuf.Message(MSG_1901)
