---Generated By Hukiry-lua Do not Edit

---商店数据
---@class MSG_1401
local MSG_1401 = {}
---@private
MSG_1401.fields = {"state","roleId","shopId","price"}
---@private
MSG_1401.fieldType = {1,3,3,2}
---@private
MSG_1401.fieldTag = {0,0,0,0}
function MSG_1401:_ctor()
	---0=接收成功，1=请求商店数据，2=支付
	self.state = 0
	---角色id
	self.roleId = 0
	---商店id
	self.shopId = 0
	---商店id
	self.price = 0
end

msg_1401 = protobuf.Message(MSG_1401)
