---Generated By Hukiry-lua Do not Edit

---排行榜
---@class MSG_1301
local MSG_1301 = {}
---@private
MSG_1301.fields = {"type","jsonDatas"}
---@private
MSG_1301.fieldType = {1,9}
---@private
MSG_1301.fieldTag = {0,0}
function MSG_1301:_ctor()
	---功能类型 1=周排行，2=月排行，3=年排行
	self.type = 0
	---json数据：角色id，角色昵称，角色等级，角色任务积分
	self.jsonDatas = ""
end

---反馈数据：存入到数据库，3个工作日内回复
---@class MSG_1302
local MSG_1302 = {}
---@private
MSG_1302.fields = {"roleId","type","content","e_mail","e_mai1l"}
---@private
MSG_1302.fieldType = {3,1,9,9,10}
---@private
MSG_1302.fieldTag = {0,0,0,0,0}
function MSG_1302:_ctor()
	---角色id
	self.roleId = 0
	---反馈问题类型：1=游戏问题，2=崩溃问题，3=充值问题，4=其他问题
	self.type = 0
	---反馈描述：30个字
	self.content = ""
	---电子邮件
	self.e_mail = ""
	---@private
	self.e_mai1l_Message = protobuf.Message(SINT32)
	---@type SINT32
	self.e_mai1l = nil
end

msg_1301 = protobuf.Message(MSG_1301)
msg_1302 = protobuf.Message(MSG_1302)
