---Generated By Hukiry-lua Do not Edit

---请求登录
---@class MSG_1001
local MSG_1001 = {}
---@private
MSG_1001.fields = {"deviceId","lang","login_type","platform"}
---@private
MSG_1001.fieldType = {9,9,1,1}
---@private
MSG_1001.fieldTag = {0,0,0,0}
function MSG_1001:_ctor()
	---首次登录的设备id
	self.deviceId = ""
	---首次登录的语言
	self.lang = ""
	---登录方式
	self.login_type = 0
	---登录平台
	self.platform = 0
end

---货币资源
---@class ITEMSRESOURCE
local ITEMSRESOURCE = {}
---@private
ITEMSRESOURCE.fields = {"type","number"}
---@private
ITEMSRESOURCE.fieldType = {1,3}
---@private
ITEMSRESOURCE.fieldTag = {0,0}
function ITEMSRESOURCE:_ctor()
	---货币类型
	self.type = 0
	---货币数量
	self.number = 0
end


---@class ITEMSPACK
local ITEMSPACK = {}
---@private
ITEMSPACK.fields = {"type","value"}
---@private
ITEMSPACK.fieldType = {1,9}
---@private
ITEMSPACK.fieldTag = {0,0}
function ITEMSPACK:_ctor()
	---货币类型
	self.type = 0
	---货币数量
	self.value = ""
end

---货币资源
---@class ITEMSMETA
local ITEMSMETA = {}
---@private
ITEMSMETA.fields = {"numberId","state"}
---@private
ITEMSMETA.fieldType = {1,1}
---@private
ITEMSMETA.fieldTag = {0,0}
function ITEMSMETA:_ctor()
	---货币类型
	self.numberId = 0
	---货币数量
	self.state = 0
end

---上传游戏数据
---@class MSG_1002
local MSG_1002 = {}
---@private
MSG_1002.fields = {"deviceId","token","timeStamp","state","items","itemsPacks"}
---@private
MSG_1002.fieldType = {9,9,12,1,10,10}
---@private
MSG_1002.fieldTag = {0,0,0,0,1,1}
function MSG_1002:_ctor()
	---绑定的设备id
	self.deviceId = ""
	---是绑定登录
	self.token = ""
	---时间搓
	self.timeStamp = 0
	---用于切换设备
	self.state = 0
	---货币数据集合
	---@private
	self.items_Message = protobuf.Message(ITEMSRESOURCE)
	---@type table<number,ITEMSRESOURCE>
	self.items = {}
	---其他属性集合
	---@private
	self.itemsPacks_Message = protobuf.Message(ITEMSPACK)
	---@type table<number,ITEMSPACK>
	self.itemsPacks = {}
end

---注销或绑定
---@class MSG_1003
local MSG_1003 = {}
---@private
MSG_1003.fields = {"state","token","deviceId","roleNick","bindAccount"}
---@private
MSG_1003.fieldType = {1,9,9,9,1}
---@private
MSG_1003.fieldTag = {0,0,0,0,0}
function MSG_1003:_ctor()
	---0=接收成功，1=注销，2=绑定, 3=切换设备, 4=修改昵称
	self.state = 0
	---上传绑定Token
	self.token = ""
	---绑定的设备id
	self.deviceId = ""
	---昵称
	self.roleNick = ""
	---绑定的账号类型
	self.bindAccount = 0
end

---心跳时间
---@class MSG_1004
local MSG_1004 = {}
---@private
MSG_1004.fields = {"timeStamp"}
---@private
MSG_1004.fieldType = {12}
---@private
MSG_1004.fieldTag = {0}
function MSG_1004:_ctor()
	---时间戳
	self.timeStamp = 0
end


---@class MSG_1005
local MSG_1005 = {}
---@private
MSG_1005.fields = {"type","number"}
---@private
MSG_1005.fieldType = {1,1}
---@private
MSG_1005.fieldTag = {0,0}
function MSG_1005:_ctor()
	---货币类型
	self.type = 0
	---货币数量
	self.number = 0
end


---@class MSG_1006
local MSG_1006 = {}
---@private
MSG_1006.fields = {"headID"}
---@private
MSG_1006.fieldType = {2}
---@private
MSG_1006.fieldTag = {0}
function MSG_1006:_ctor()
	---修改头像id
	self.headID = 0
end

msg_1001 = protobuf.Message(MSG_1001)
itemsResource = protobuf.Message(ITEMSRESOURCE)
itemsPack = protobuf.Message(ITEMSPACK)
itemsMeta = protobuf.Message(ITEMSMETA)
msg_1002 = protobuf.Message(MSG_1002)
msg_1003 = protobuf.Message(MSG_1003)
msg_1004 = protobuf.Message(MSG_1004)
msg_1005 = protobuf.Message(MSG_1005)
msg_1006 = protobuf.Message(MSG_1006)
