---Generated By Hukiry-lua Do not Edit


---@class MAILDATA
local MAILDATA = {}
---@private
MAILDATA.fields = {"id","title","isLife","content","rewards"}
---@private
MAILDATA.fieldType = {2,9,7,9,9}
---@private
MAILDATA.fieldTag = {0,0,0,0,0}
function MAILDATA:_ctor()
	---邮件和公告id
	self.id = 0
	---邮件和公告标题，角色昵称
	self.title = ""
	---邮件和公告内容
	self.isLife = false
	---邮件和公告内容
	self.content = ""
	---邮件和公告奖励：后面用于充值补发json数据
	self.rewards = ""
end

------邮件和公告数据操作
---@class MSG_1101
local MSG_1101 = {}
---@private
MSG_1101.fields = {"state","type","roleId","id","lanCode","mails"}
---@private
MSG_1101.fieldType = {1,1,3,2,9,10}
---@private
MSG_1101.fieldTag = {0,0,0,0,0,1}
function MSG_1101:_ctor()
	---0=接收成功，1=请求数据，2=读取，3=删除，4=领取
	self.state = 0
	---功能类型
	self.type = 0
	---角色id
	self.roleId = 0
	---邮件和公告id 用于已读
	self.id = 0
	---公告语言代码
	self.lanCode = ""
	---邮件和公告id
	---@private
	self.mails_Message = protobuf.Message(MAILDATA)
	---@type table<number,MAILDATA>
	self.mails = {}
end

mailData = protobuf.Message(MAILDATA)
msg_1101 = protobuf.Message(MSG_1101)
