---Generated By Hukiry-lua Do not Edit

---元宇宙信息：发起或点赞
---@class METAINFO
local METAINFO = {}
---@private
METAINFO.fields = {"friendId","likeNum","numberId","state","comment"}
---@private
METAINFO.fieldType = {3,3,1,1,9}
---@private
METAINFO.fieldTag = {0,0,0,0,0}
function METAINFO:_ctor()
	---发起者的id
	self.friendId = 0
	---地图的点赞数量
	self.likeNum = 0
	---发起者地图id
	self.numberId = 0
	---挑战状态，0=未接受挑战，1=接受过挑战
	self.state = 0
	---地图的所有评论
	self.comment = ""
end

---元宇宙数据:元宇宙表，发给谁，数据就存入给对方
---@class MSG_1601
local MSG_1601 = {}
---@private
MSG_1601.fields = {"state","roleId","friendId","numberId","comment","metaInfos"}
---@private
MSG_1601.fieldType = {1,3,3,1,9,10}
---@private
MSG_1601.fieldTag = {0,0,0,0,0,1}
function MSG_1601:_ctor()
	---0=对战消息，1=发起挑战，2=点赞，3=评论
	self.state = 0
	---我的角色id
	self.roleId = 0
	---好友角色id
	self.friendId = 0
	---好友点赞的地图id
	self.numberId = 0
	---好友发起评论
	self.comment = ""
	---地图返回的挑战消息
	---@private
	self.metaInfos_Message = protobuf.Message(METAINFO)
	---@type table<number,METAINFO>
	self.metaInfos = {}
end

MetaInfo = protobuf.Message(METAINFO)
msg_1601 = protobuf.Message(MSG_1601)
