local _res = EAtlasResPath;
---@class ESpriteAtlasResource
ESpriteAtlasResource = {
    ['role_1'] = _res.UIHead,['role_10'] = _res.UIHead,['role_11'] = _res.UIHead,
    ['role_12'] = _res.UIHead,['role_13'] = _res.UIHead,['role_14'] = _res.UIHead,
    ['role_15'] = _res.UIHead,['role_16'] = _res.UIHead,['role_17'] = _res.UIHead,
    ['role_18'] = _res.UIHead,['role_19'] = _res.UIHead,['role_2'] = _res.UIHead,
    ['role_20'] = _res.UIHead,['role_21'] = _res.UIHead,['role_22'] = _res.UIHead,
    ['role_23'] = _res.UIHead,['role_24'] = _res.UIHead,['role_25'] = _res.UIHead,
    ['role_26'] = _res.UIHead,['role_27'] = _res.UIHead,['role_28'] = _res.UIHead,
    ['role_29'] = _res.UIHead,['role_3'] = _res.UIHead,['role_30'] = _res.UIHead,
    ['role_4'] = _res.UIHead,['role_5'] = _res.UIHead,['role_6'] = _res.UIHead,
    ['role_7'] = _res.UIHead,['role_8'] = _res.UIHead,['role_9'] = _res.UIHead,
    ['baseboard'] = _res.Item,['blue'] = _res.Item,['blue1'] = _res.Item,
    ['bomb'] = _res.Item,['bowl'] = _res.Item,['bowl_counter'] = _res.Item,
    ['bowl_door'] = _res.Item,['bowl_shadow'] = _res.Item,['box'] = _res.Item,
    ['box_blue'] = _res.Item,['box_blue_horizontal'] = _res.Item,['box_blue_xie'] = _res.Item,
    ['box_green'] = _res.Item,['box_green_horizontal'] = _res.Item,['box_green_xie'] = _res.Item,
    ['box_horizontal'] = _res.Item,['box_purple'] = _res.Item,['box_purple_horizontal'] = _res.Item,
    ['box_purple_xie'] = _res.Item,['box_red'] = _res.Item,['box_red_horizontal'] = _res.Item,
    ['box_red_xie'] = _res.Item,['box_xie'] = _res.Item,['box_yellow'] = _res.Item,
    ['box_yellow_horizontal'] = _res.Item,['box_yellow_xie'] = _res.Item,['bubble_0'] = _res.Item,
    ['bubble_1'] = _res.Item,['bubble_2'] = _res.Item,['butterfly'] = _res.Item,
    ['chicken'] = _res.Item,['chicken_egg'] = _res.Item,['cloud'] = _res.Item,
    ['CloudFlower'] = _res.Item,['cyan'] = _res.Item,['cyan1'] = _res.Item,
    ['dragonfly'] = _res.Item,['dragon_blue1'] = _res.Item,['dragon_blue2'] = _res.Item,
    ['dragon_card'] = _res.Item,['dragon_house'] = _res.Item,['egg'] = _res.Item,
    ['flowerbed'] = _res.Item,['glass_0'] = _res.Item,['glass_1'] = _res.Item,
    ['green'] = _res.Item,['green1'] = _res.Item,['greenMoss'] = _res.Item,
    ['horizontal_rocket'] = _res.Item,['icon_10001'] = _res.Item,['icon_10003'] = _res.Item,
    ['icon_10004'] = _res.Item,['icon_10005'] = _res.Item,['item_bows'] = _res.Item,
    ['item_cap'] = _res.Item,['item_gun'] = _res.Item,['item_hammer'] = _res.Item,
    ['item_jar'] = _res.Item,['item_shadow'] = _res.Item,['jar_0'] = _res.Item,
    ['jar_1'] = _res.Item,['jar_blue'] = _res.Item,['jar_counter'] = _res.Item,
    ['jar_green'] = _res.Item,['jar_red'] = _res.Item,['jar_shadow'] = _res.Item,
    ['jar_yellow'] = _res.Item,['jinbi'] = _res.Item,['life_fill'] = _res.Item,
    ['life_heart'] = _res.Item,['life_tag'] = _res.Item,['pikachu'] = _res.Item,
    ['pond'] = _res.Item,['purple'] = _res.Item,['purple1'] = _res.Item,
    ['rainbow_ball'] = _res.Item,['red'] = _res.Item,['red1'] = _res.Item,
    ['rocket'] = _res.Item,['safeBox'] = _res.Item,['safeBox_gold'] = _res.Item,
    ['shell'] = _res.Item,['shell_pearl'] = _res.Item,['snail'] = _res.Item,
    ['solo01'] = _res.Item,['stonePier'] = _res.Item,['stone_carve'] = _res.Item,
    ['vertical_rocket'] = _res.Item,['watermelon_0'] = _res.Item,['watermelon_1'] = _res.Item,
    ['woodenPeg'] = _res.Item,['yellow'] = _res.Item,['yellow1'] = _res.Item,
}
