//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DG_Tweening_DOTweenAnimation_AnimationTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(DG.Tweening.DOTweenAnimation.AnimationType));
		L.RegVar("None", get_None, null);
		L.RegVar("Move", get_Move, null);
		L.RegVar("LocalMove", get_LocalMove, null);
		L.RegVar("Rotate", get_Rotate, null);
		L.RegVar("LocalRotate", get_LocalRotate, null);
		L.RegVar("Scale", get_Scale, null);
		L.RegVar("Color", get_Color, null);
		L.RegVar("Fade", get_Fade, null);
		L.RegVar("Text", get_Text, null);
		L.RegVar("PunchPosition", get_PunchPosition, null);
		L.RegVar("PunchRotation", get_PunchRotation, null);
		L.RegVar("PunchScale", get_PunchScale, null);
		L.RegVar("ShakePosition", get_ShakePosition, null);
		L.RegVar("ShakeRotation", get_ShakeRotation, null);
		L.RegVar("ShakeScale", get_ShakeScale, null);
		L.RegVar("CameraAspect", get_CameraAspect, null);
		L.RegVar("CameraBackgroundColor", get_CameraBackgroundColor, null);
		L.RegVar("CameraFieldOfView", get_CameraFieldOfView, null);
		L.RegVar("CameraOrthoSize", get_CameraOrthoSize, null);
		L.RegVar("CameraPixelRect", get_CameraPixelRect, null);
		L.RegVar("CameraRect", get_CameraRect, null);
		L.RegVar("UIWidthHeight", get_UIWidthHeight, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<DG.Tweening.DOTweenAnimation.AnimationType>.Check = CheckType;
		StackTraits<DG.Tweening.DOTweenAnimation.AnimationType>.Push = Push;
	}

	static void Push(IntPtr L, DG.Tweening.DOTweenAnimation.AnimationType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(DG.Tweening.DOTweenAnimation.AnimationType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Move(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.Move);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LocalMove(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.LocalMove);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Rotate(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.Rotate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LocalRotate(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.LocalRotate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scale(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.Scale);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Color(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.Color);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Fade(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.Fade);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Text(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.Text);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PunchPosition(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.PunchPosition);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PunchRotation(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.PunchRotation);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PunchScale(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.PunchScale);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ShakePosition(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.ShakePosition);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ShakeRotation(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.ShakeRotation);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ShakeScale(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.ShakeScale);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraAspect(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.CameraAspect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraBackgroundColor(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.CameraBackgroundColor);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraFieldOfView(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.CameraFieldOfView);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraOrthoSize(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.CameraOrthoSize);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraPixelRect(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.CameraPixelRect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CameraRect(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.CameraRect);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIWidthHeight(IntPtr L)
	{
		ToLua.Push(L, DG.Tweening.DOTweenAnimation.AnimationType.UIWidthHeight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		DG.Tweening.DOTweenAnimation.AnimationType o = (DG.Tweening.DOTweenAnimation.AnimationType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

