//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_SpriteSortPointWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.SpriteSortPoint));
		L.RegVar("Center", get_Center, null);
		L.RegVar("Pivot", get_Pivot, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.SpriteSortPoint>.Check = CheckType;
		StackTraits<UnityEngine.SpriteSortPoint>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.SpriteSortPoint arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.SpriteSortPoint), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Center(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SpriteSortPoint.Center);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Pivot(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SpriteSortPoint.Pivot);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.SpriteSortPoint o = (UnityEngine.SpriteSortPoint)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

