//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_AspectRatioFitter_AspectModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.AspectRatioFitter.AspectMode));
		L.RegVar("None", get_None, null);
		L.RegVar("WidthControlsHeight", get_WidthControlsHeight, null);
		L.RegVar("HeightControlsWidth", get_HeightControlsWidth, null);
		L.RegVar("FitInParent", get_FitInParent, null);
		L.RegVar("EnvelopeParent", get_EnvelopeParent, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.UI.AspectRatioFitter.AspectMode>.Check = CheckType;
		StackTraits<UnityEngine.UI.AspectRatioFitter.AspectMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.UI.AspectRatioFitter.AspectMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.UI.AspectRatioFitter.AspectMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.AspectRatioFitter.AspectMode.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_WidthControlsHeight(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.AspectRatioFitter.AspectMode.WidthControlsHeight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HeightControlsWidth(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.AspectRatioFitter.AspectMode.HeightControlsWidth);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_FitInParent(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.AspectRatioFitter.AspectMode.FitInParent);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EnvelopeParent(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.AspectRatioFitter.AspectMode.EnvelopeParent);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.AspectRatioFitter.AspectMode o = (UnityEngine.UI.AspectRatioFitter.AspectMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

