//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_SpriteTileModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.SpriteTileMode));
		L.RegVar("Continuous", get_Continuous, null);
		L.RegVar("Adaptive", get_Adaptive, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.SpriteTileMode>.Check = CheckType;
		StackTraits<UnityEngine.SpriteTileMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.SpriteTileMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.SpriteTileMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Continuous(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SpriteTileMode.Continuous);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Adaptive(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.SpriteTileMode.Adaptive);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.SpriteTileMode o = (UnityEngine.SpriteTileMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

