//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_InputField_CharacterValidationWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.InputField.CharacterValidation));
		L.RegVar("None", get_None, null);
		L.RegVar("Integer", get_Integer, null);
		L.RegVar("Decimal", get_Decimal, null);
		L.RegVar("Alphanumeric", get_Alphanumeric, null);
		L.RegVar("Name", get_Name, null);
		L.RegVar("EmailAddress", get_EmailAddress, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.UI.InputField.CharacterValidation>.Check = CheckType;
		StackTraits<UnityEngine.UI.InputField.CharacterValidation>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.UI.InputField.CharacterValidation arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.UI.InputField.CharacterValidation), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.CharacterValidation.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Integer(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.CharacterValidation.Integer);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Decimal(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.CharacterValidation.Decimal);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Alphanumeric(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.CharacterValidation.Alphanumeric);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Name(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.CharacterValidation.Name);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EmailAddress(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.InputField.CharacterValidation.EmailAddress);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.InputField.CharacterValidation o = (UnityEngine.UI.InputField.CharacterValidation)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

