//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_EventSystems_PointerEventData_InputButtonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.EventSystems.PointerEventData.InputButton));
		L.RegVar("Left", get_Left, null);
		L.RegVar("Right", get_Right, null);
		L.RegVar("Middle", get_Middle, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.EventSystems.PointerEventData.InputButton>.Check = CheckType;
		StackTraits<UnityEngine.EventSystems.PointerEventData.InputButton>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.EventSystems.PointerEventData.InputButton arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.EventSystems.PointerEventData.InputButton), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Left(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.PointerEventData.InputButton.Left);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Right(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.PointerEventData.InputButton.Right);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Middle(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.EventSystems.PointerEventData.InputButton.Middle);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.EventSystems.PointerEventData.InputButton o = (UnityEngine.EventSystems.PointerEventData.InputButton)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

